---
title: Java并发：线程的执行结果和异常
abbrlink: 62788
date: 2022-08-07 01:54:46
description: 处理线程执行过程中抛出的异常以及返回的结果。
categories:
  - Java
  - 并发
---

# 利用 Future 获取线程执行结果和处理异常

**简介：**

如果当前任务需要另外的某一个任务执行完毕获取到返回值后才能继续执行，但是这个另外的任务又比较耗时，那么可以使用 Future 类将这个任务的返回结果包装起来，然后当前线程先去做点其他的事情，等到 Future 拿到结果之后再执行那部分的逻辑。这个被包装的对象就是 `Callable`。

**简而言之：**如果有个很耗时的方法的需要执行，那么先开个线程让它执行，当前线程先做点其他的事情，不要一直在哪里傻等

**Callable 介绍：**

```java
@FunctionalInterface
public interface Callable<V> {
    /**
     * Computes a result, or throws an exception if unable to do so.
     *
     * @return computed result
     * @throws Exception if unable to compute a result
     */
    V call() throws Exception;
}
```

Callable 是一个接口，跟 Runnable 一样用来包装要执行的任务，不同的是 Callable 接口可以拥有返回值和向外抛出异常。

{% note modern primary no-icon%}
**Future 的使用：**
{% endnote %}

```java
public static void main(String[] args) {
    final ExecutorService service = Executors.newFixedThreadPool(1);
    final Future<Integer> future = service.submit(new Task());
    try {
        System.out.println(future.get());
    } catch (InterruptedException | ExecutionException e) {
        throw new RuntimeException(e);
    }
}

private static final class Task implements Callable<Integer> {
    @Override
    public Integer call() throws Exception {
        return new Random().nextInt();
    }
}
```

get 方法的行为取决于 Callable 任务的状态，只有以下五种情况：

1. 任务正常完成：gei 方法会立即返回结果
2. 任务尚未完成（可能是还没开始或执行中）：get将阻塞直到任务完成并返回结果
3. 任务执行过程中抛出 Exception：get方法会抛出 ExecutionException
   这里的异常是 call 方法产生的异常，不管 call 方法抛出了什么样的异常都会被 get 方法接收到，但是 get 方法只会抛出 ExecutionException 异常。
4. 任务被取消：get 方法会抛出 CancellationException
5. 任务超时：get 方法有一个重载方法，可以传入延迟时间，如果时间到了还没有获得结果，get方法就会抛出 TimeOutException。

**Future 的其他方法介绍：**

```java
public interface Future<V> {

    /** 
     * 尝试取消任务，如果任务已经完成、已取消或其他原因无法取消，则失败。 
     * 1、如果任务还没开始执行，则该任务不应该运行 
     * 2、如果任务已经开始执行，由参数mayInterruptIfRunning来决定执行该任务的线程是否应该被中断，这只是终止任务的一种尝试。
          若mayInterruptIfRunning为true，则会立即中断执行任务的线程并返回true
          若mayInterruptIfRunning为false，则会返回true且不会中断任务执行线程。
     * 3、调用这个方法后，以后对isDone方法调用都返回true。 
     * 4、如果这个方法返回true,以后对isCancelled返回true。 
     */ 
    boolean cancel(boolean mayInterruptIfRunning);

    /** 
     * 判断任务是否被取消了，如果调用了cancel()则返回true 
     */
    boolean isCancelled();

    /** 
     * 如果任务完成，则返回ture 
     * 任务完成包含正常终止、异常、取消任务。在这些情况下都返回true 
     */ 
    boolean isDone();

    V get() throws InterruptedException, ExecutionException;
    V get(long timeout, TimeUnit unit)
        throws InterruptedException, ExecutionException, TimeoutException;
}
```

{% note modern primary no-icon%}
**FutureTask 的使用：**
{% endnote %}

上面的例子使用的是线程池的 submit 方法创建 Future 对象，现在介绍一种由普通线程创建的 Future 对象：FutureTask。

Thread 类是只能传入 Runnable 方法去执行的，而现在又需要一个 Future 对象，显而易见的我们需要一个类同时实现 Future 和 Runnable 对象。

![FutureTask类关系图](https://wrp-blog-image.oss-cn-beijing.aliyuncs.com/blog-images/FutureTask类关系图.png)

这个类的使用方式也很简单，需要 Runnable 对象的时候就把它当 Runnable 去用，需要 Future 的时候就把它当 Future 去用。

```java
public static void main(String[] args) {
    final FutureTask<Integer> futureTask = new FutureTask<>(new Task());
    new Thread(futureTask).start();
    try {
        System.out.println(futureTask.get());
    } catch (InterruptedException | ExecutionException e) {
        throw new RuntimeException(e);
    }
}
```

---

**巨人的肩膀：**

[并发编程之Future&FutureTask深入解析](https://www.51cto.com/article/633900.html)